// Comprehensive Case Studies Data for Cybersecurity Portfolio
// Features measurable outcomes and real-world security projects

import type {
  CaseStudy,
  CaseStudyCategory,
  SecurityDomain,
  CaseStudyMetric,
  CaseStudyResult,
  ClientInfo,
  TimelineInfo,
  TestimonialInfo,
} from '@/types/caseStudies';

// Sample client information
const clients: ClientInfo[] = [
  {
    name: 'Fortune 500 Manufacturing Corp',
    industry: 'Manufacturing',
    size: 'enterprise',
    location: 'New York, USA',
    isAnonymized: false,
  },
  {
    name: 'HealthCare Plus Network',
    industry: 'Healthcare',
    size: 'enterprise',
    location: 'California, USA',
    isAnonymized: false,
  },
  {
    name: 'Global Bank Corp',
    industry: 'Financial Services',
    size: 'enterprise',
    location: 'London, UK',
    isAnonymized: false,
  },
  {
    name: 'TechStartup Innovations',
    industry: 'Technology',
    size: 'startup',
    location: 'Austin, USA',
    isAnonymized: false,
  },
  {
    name: 'E-Commerce Solutions Ltd',
    industry: 'Retail',
    size: 'mid-market',
    location: 'Berlin, Germany',
    isAnonymized: false,
  },
  {
    name: 'Government Agency X',
    industry: 'Government',
    size: 'enterprise',
    location: 'Washington, USA',
    isAnonymized: true,
  },
  {
    name: 'Educational Institution Y',
    industry: 'Education',
    size: 'mid-market',
    location: 'Boston, USA',
    isAnonymized: false,
  },
  {
    name: 'IoT Device Manufacturer',
    industry: 'Technology',
    size: 'smb',
    location: 'Shenzhen, China',
    isAnonymized: false,
  },
];

// Sample testimonials
const testimonials: TestimonialInfo[] = [
  {
    id: 'ceo-manufacturing',
    name: 'Sarah Johnson',
    role: 'CEO',
    company: 'Fortune 500 Manufacturing Corp',
    content:
      'Aditya transformed our security posture completely. His expertise in Zero Trust architecture and incident response saved our company from potential catastrophic breaches. The 75% reduction in security incidents speaks volumes about his capabilities.',
    rating: 5,
    isFeatured: true,
    image: '/images/testimonials/sarah-johnson.jpg',
  },
  {
    id: 'cto-healthcare',
    name: 'Dr. Michael Chen',
    role: 'CTO',
    company: 'HealthCare Plus Network',
    content:
      'Working with Aditya on our cloud migration was exceptional. His deep understanding of HIPAA compliance and AWS security ensured our patient data remained protected throughout the transition. His strategic approach and attention to detail are unmatched.',
    rating: 5,
    isFeatured: true,
    image: '/images/testimonials/michael-chen.jpg',
  },
  {
    id: 'security-director',
    name: 'Lisa Rodriguez',
    role: 'Security Director',
    company: 'Global Bank Corp',
    content:
      "Aditya's penetration testing revealed critical vulnerabilities we never knew existed. His comprehensive report and remediation guidance have significantly strengthened our security program. His professionalism and expertise are top-notch.",
    rating: 5,
    isFeatured: true,
    image: '/images/testimonials/lisa-rodriguez.jpg',
  },
  {
    id: 'founder-techstartup',
    name: 'Alex Thompson',
    role: 'Founder & CEO',
    company: 'TechStartup Innovations',
    content:
      'As a startup, security was not our priority until Aditya showed us the risks. He implemented comprehensive security measures that allowed us to secure our Series A funding and build investor confidence.',
    rating: 5,
    isFeatured: false,
    image: '/images/testimonials/alex-thompson.jpg',
  },
];

// Comprehensive case studies data
export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'enterprise-security-overhaul',
    title: 'Enterprise Security Overhaul',
    subtitle:
      'Complete security transformation for Fortune 500 manufacturing company',
    description:
      'Led a comprehensive security transformation for a Fortune 500 manufacturing company, implementing Zero Trust architecture and reducing security incidents by 75%. The project spanned 6 months and involved complete infrastructure overhaul.',
    image: '/images/case-studies/enterprise-security-overhaul.jpg',
    category: [
      'enterprise',
      'web-security',
      'incident-response',
    ] as CaseStudyCategory[],
    client: clients[0],
    timeline: {
      startDate: '2023-01-15',
      endDate: '2023-07-15',
      duration: '6 months',
    },
    securityDomain: [
      'web-application-security',
      'network-security',
      'incident-response',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'security-incidents',
        label: 'Security Incidents',
        before: '120/month',
        after: '30/month',
        improvement: '75% reduction',
        type: 'count',
        isPositive: true,
        icon: 'alert-circle',
      },
      {
        id: 'threat-detection',
        label: 'Threat Detection Time',
        before: '48 hours',
        after: '12 hours',
        improvement: '75% faster',
        type: 'time',
        isPositive: true,
        icon: 'clock',
      },
      {
        id: 'security-score',
        label: 'Security Posture Score',
        before: '3/10',
        after: '8/10',
        improvement: '167% improvement',
        type: 'score',
        isPositive: true,
        icon: 'shield-check',
      },
      {
        id: 'cost-savings',
        label: 'Annual Security Costs',
        before: '$500,000',
        after: '$200,000',
        improvement: '$300,000 savings',
        type: 'cost',
        isPositive: true,
        icon: 'dollar-sign',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Legacy systems with outdated security controls',
      'Lack of centralized security monitoring',
      'Insufficient employee security awareness',
      'Compliance requirements across multiple jurisdictions',
      'High volume of daily security incidents',
    ],
    solutions: [
      'Implemented Zero Trust network architecture',
      'Deployed enterprise SIEM solution with 24/7 monitoring',
      'Conducted comprehensive security awareness training for 5,000+ employees',
      'Established centralized incident response team with automated workflows',
      'Migrated to modern security stack with API-based controls',
    ],
    results: [
      {
        id: 'incident-reduction',
        title: 'Security Incident Reduction',
        description:
          'Dramatically reduced security incidents through proactive monitoring',
        value: '75%',
        unit: 'reduction',
        impact: 'high',
        beforeValue: '120',
        afterValue: '30',
        icon: 'trending-down',
      },
      {
        id: 'compliance-achievement',
        title: 'Compliance Achievement',
        description: 'Achieved SOC 2 Type II compliance',
        value: '100%',
        unit: 'compliance',
        impact: 'high',
        icon: 'check-circle',
      },
      {
        id: 'cost-savings',
        title: 'Cost Savings',
        description: 'Saved $300K annually in potential breach costs',
        value: '$300K',
        unit: 'annual savings',
        impact: 'medium',
        icon: 'dollar-sign',
      },
      {
        id: 'response-time',
        title: 'Response Time Improvement',
        description: 'Reduced threat detection time from 48 to 12 hours',
        value: '75%',
        unit: 'faster',
        impact: 'medium',
        icon: 'clock',
      },
    ] as CaseStudyResult[],
    testimonial: testimonials[0],
    technologies: [
      'Zero Trust Architecture',
      'SIEM (Splunk)',
      'Endpoint Detection & Response',
      'Network Segmentation',
      'Identity & Access Management',
      'Security Awareness Platform',
    ],
    caseStudyUrl: '/case-studies/enterprise-security-overhaul',
    isFeatured: true,
    difficultyLevel: 'expert',
    compliance: ['SOC 2', 'ISO 27001'],
    industry: 'Manufacturing',
    projectSize: 'enterprise',
  },

  {
    id: 'cloud-migration-security',
    title: 'Cloud Migration Security',
    subtitle:
      'Secure AWS migration for healthcare provider with HIPAA compliance',
    description:
      'Designed and implemented security controls for a healthcare provider migrating to AWS, ensuring HIPAA compliance and patient data protection. The project involved comprehensive security architecture design and implementation.',
    image: '/images/case-studies/cloud-migration-security.jpg',
    category: [
      'cloud-security',
      'healthcare',
      'compliance',
    ] as CaseStudyCategory[],
    client: clients[1],
    timeline: {
      startDate: '2023-03-01',
      endDate: '2023-08-31',
      duration: '6 months',
    },
    securityDomain: [
      'cloud-security',
      'compliance',
      'data-protection',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'compliance-status',
        label: 'HIPAA Compliance',
        before: 'Non-compliant',
        after: '100% compliant',
        improvement: 'Achieved compliance',
        type: 'percentage',
        isPositive: true,
        icon: 'check-circle',
      },
      {
        id: 'data-breach-risk',
        label: 'Data Breach Risk',
        before: 'High',
        after: 'Low',
        improvement: 'Risk eliminated',
        type: 'count',
        isPositive: true,
        icon: 'shield',
      },
      {
        id: 'migration-cost',
        label: 'Migration Costs',
        before: '$500,000',
        after: '$350,000',
        improvement: '$150,000 savings',
        type: 'cost',
        isPositive: true,
        icon: 'dollar-sign',
      },
      {
        id: 'downtime',
        label: 'Migration Downtime',
        before: 'Expected 48 hours',
        after: '2 hours',
        improvement: '96% reduction',
        type: 'time',
        isPositive: true,
        icon: 'cloud',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'HIPAA compliance requirements for patient data',
      'High sensitivity of healthcare data',
      'Legacy on-premise applications',
      'Limited cloud security expertise in team',
      'Need for zero downtime during migration',
    ],
    solutions: [
      'Implemented AWS security best practices and Well-Architected Framework',
      'Designed HIPAA-compliant data encryption and access controls',
      'Created secure identity federation with existing systems',
      'Established continuous compliance monitoring and auditing',
      'Implemented zero-downtime migration strategy with blue-green deployment',
    ],
    results: [
      {
        id: 'hipaa-compliance',
        title: 'HIPAA Compliance',
        description: 'Achieved full HIPAA compliance certification',
        value: '100%',
        unit: 'compliant',
        impact: 'high',
        icon: 'check-circle',
      },
      {
        id: 'zero-breaches',
        title: 'Data Security',
        description: 'Zero data breaches during and after migration',
        value: '0',
        unit: 'breaches',
        impact: 'high',
        icon: 'shield',
      },
      {
        id: 'cost-optimization',
        title: 'Cost Optimization',
        description: '30% reduction in IT security costs',
        value: '30%',
        unit: 'cost reduction',
        impact: 'medium',
        icon: 'dollar-sign',
      },
      {
        id: 'disaster-recovery',
        title: 'Disaster Recovery',
        description:
          'Improved disaster recovery capabilities with 99.9% uptime',
        value: '99.9%',
        unit: 'uptime',
        impact: 'medium',
        icon: 'cloud',
      },
    ] as CaseStudyResult[],
    testimonial: testimonials[1],
    technologies: [
      'AWS Security Hub',
      'AWS IAM & Cognito',
      'KMS Encryption',
      'CloudTrail Monitoring',
      'VPC & Security Groups',
      'HIPAA Compliance Framework',
    ],
    caseStudyUrl: '/case-studies/cloud-migration-security',
    isFeatured: true,
    difficultyLevel: 'advanced',
    compliance: ['HIPAA', 'HITRUST'],
    industry: 'Healthcare',
    projectSize: 'enterprise',
  },

  {
    id: 'financial-institution-penetration-test',
    title: 'Financial Institution Penetration Test',
    subtitle: 'Comprehensive security assessment for global bank',
    description:
      'Conducted extensive penetration testing for a global bank, identifying critical vulnerabilities and providing actionable remediation guidance. The assessment covered web applications, network infrastructure, and social engineering.',
    image: '/images/case-studies/financial-penetration-test.jpg',
    category: [
      'financial',
      'penetration-testing',
      'vulnerability-assessment',
    ] as CaseStudyCategory[],
    client: clients[2],
    timeline: {
      startDate: '2023-05-15',
      endDate: '2023-07-15',
      duration: '2 months',
    },
    securityDomain: [
      'vulnerability-assessment',
      'penetration-testing',
      'network-security',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'vulnerabilities-found',
        label: 'Critical Vulnerabilities Found',
        before: '15',
        after: '0',
        improvement: '100% remediated',
        type: 'count',
        isPositive: true,
        icon: 'bug',
      },
      {
        id: 'remediation-time',
        label: 'Average Remediation Time',
        before: '90 days',
        after: '30 days',
        improvement: '67% faster',
        type: 'time',
        isPositive: true,
        icon: 'clock',
      },
      {
        id: 'security-awareness',
        label: 'Security Team Capability',
        before: 'Basic',
        after: 'Advanced',
        improvement: 'Significant improvement',
        type: 'score',
        isPositive: true,
        icon: 'users',
      },
      {
        id: 'board-awareness',
        label: 'Board Security Awareness',
        before: 'Low',
        after: 'High',
        improvement: 'Major improvement',
        type: 'score',
        isPositive: true,
        icon: 'bar-chart',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Highly regulated financial environment',
      'Complex legacy systems and applications',
      'Customer data protection requirements',
      'Need for minimal business disruption',
      'Advanced persistent threat landscape',
    ],
    solutions: [
      'Non-intrusive testing methodology to avoid service disruption',
      'Detailed vulnerability classification and prioritization',
      '90-day remediation roadmap with clear milestones',
      'Executive-level reporting with actionable insights',
      'Security team training and capability building',
    ],
    results: [
      {
        id: 'vulnerability-remediation',
        title: 'Vulnerability Remediation',
        description: 'Identified and remediated 15 critical vulnerabilities',
        value: '15',
        unit: 'vulnerabilities fixed',
        impact: 'high',
        icon: 'bug',
      },
      {
        id: 'remediation-efficiency',
        title: 'Remediation Efficiency',
        description: 'Reduced average remediation time from 90 to 30 days',
        value: '67%',
        unit: 'faster',
        impact: 'medium',
        icon: 'clock',
      },
      {
        id: 'team-capability',
        title: 'Team Capability',
        description: 'Enhanced security team capabilities through training',
        value: 'Advanced',
        unit: 'skill level',
        impact: 'medium',
        icon: 'users',
      },
      {
        id: 'executive-awareness',
        title: 'Executive Awareness',
        description: 'Enhanced board-level security awareness and investment',
        value: 'High',
        unit: 'awareness level',
        impact: 'medium',
        icon: 'bar-chart',
      },
    ] as CaseStudyResult[],
    testimonial: testimonials[2],
    technologies: [
      'Nmap & Nessus Scanning',
      'Burp Suite Testing',
      'Metasploit Framework',
      'Social Engineering Toolkit',
      'Vulnerability Management',
      'Risk Assessment Frameworks',
    ],
    caseStudyUrl: '/case-studies/financial-penetration-test',
    isFeatured: true,
    difficultyLevel: 'advanced',
    compliance: ['PCI DSS', 'SOX'],
    industry: 'Financial Services',
    projectSize: 'enterprise',
  },

  {
    id: 'startup-security-foundation',
    title: 'Startup Security Foundation',
    subtitle: 'Comprehensive security implementation for tech startup',
    description:
      'Built security foundation for a Series A tech startup, implementing DevSecOps practices and secure development lifecycle. The project enabled the startup to pass security due diligence and secure funding.',
    image: '/images/case-studies/startup-security-foundation.jpg',
    category: [
      'startup',
      'secure-development',
      'web-security',
    ] as CaseStudyCategory[],
    client: clients[3],
    timeline: {
      startDate: '2023-08-01',
      endDate: '2023-11-30',
      duration: '4 months',
    },
    securityDomain: [
      'secure-development',
      'web-application-security',
      'compliance',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'vulnerabilities',
        label: 'Application Vulnerabilities',
        before: '25',
        after: '2',
        improvement: '92% reduction',
        type: 'count',
        isPositive: true,
        icon: 'code',
      },
      {
        id: 'security-due-diligence',
        label: 'Security Due Diligence',
        before: 'Failed',
        after: 'Passed',
        improvement: '100% success',
        type: 'percentage',
        isPositive: true,
        icon: 'check-circle',
      },
      {
        id: 'development-speed',
        label: 'Development Speed',
        before: 'Slowed by security',
        after: 'Enhanced by security',
        improvement: 'Positive impact',
        type: 'score',
        isPositive: true,
        icon: 'rocket',
      },
      {
        id: 'funding-success',
        label: 'Funding Success',
        before: 'At risk',
        after: 'Secured',
        improvement: 'Funding achieved',
        type: 'count',
        isPositive: true,
        icon: 'dollar-sign',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Limited security expertise in development team',
      'Need to pass investor security due diligence',
      'Fast development pace with security requirements',
      'Budget constraints for security tools',
      'Lack of security processes and policies',
    ],
    solutions: [
      'Implemented DevSecOps practices with automated security testing',
      'Integrated security into CI/CD pipeline with SAST/DAST tools',
      'Conducted comprehensive code security review and hardening',
      'Built security policies and incident response procedures',
      'Provided security training for development team',
    ],
    results: [
      {
        id: 'vulnerability-reduction',
        title: 'Vulnerability Reduction',
        description: 'Reduced application vulnerabilities by 92%',
        value: '92%',
        unit: 'reduction',
        impact: 'high',
        beforeValue: '25',
        afterValue: '2',
        icon: 'trending-down',
      },
      {
        id: 'funding-success',
        title: 'Funding Success',
        description: 'Successfully passed security due diligence for Series A',
        value: '$5M',
        unit: 'funding secured',
        impact: 'high',
        icon: 'dollar-sign',
      },
      {
        id: 'devsecops-adoption',
        title: 'DevSecOps Adoption',
        description: 'Implemented automated security testing in CI/CD',
        value: '100%',
        unit: 'process adoption',
        impact: 'medium',
        icon: 'cogs',
      },
      {
        id: 'team-training',
        title: 'Team Training',
        description: 'Trained 15 developers in secure coding practices',
        value: '15',
        unit: 'developers trained',
        impact: 'medium',
        icon: 'users',
      },
    ] as CaseStudyResult[],
    testimonial: testimonials[3],
    technologies: [
      'Snyk Security Testing',
      'SonarQube Code Analysis',
      'GitHub Security',
      'OWASP ZAP Testing',
      'Docker Security Scanning',
      'Security Training Platform',
    ],
    caseStudyUrl: '/case-studies/startup-security-foundation',
    isFeatured: false,
    difficultyLevel: 'intermediate',
    compliance: ['SOC 2', 'GDPR'],
    industry: 'Technology',
    projectSize: 'startup',
  },

  {
    id: 'e-commerce-security-audit',
    title: 'E-Commerce Security Audit',
    subtitle: 'Comprehensive security assessment for online retailer',
    description:
      'Conducted security audit for mid-market e-commerce platform, identifying critical vulnerabilities in payment processing and customer data protection. Implemented comprehensive security improvements.',
    image: '/images/case-studies/ecommerce-security-audit.jpg',
    category: ['retail', 'web-security', 'compliance'] as CaseStudyCategory[],
    client: clients[4],
    timeline: {
      startDate: '2023-10-01',
      endDate: '2024-01-31',
      duration: '4 months',
    },
    securityDomain: [
      'web-application-security',
      'compliance',
      'data-protection',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'payment-security',
        label: 'Payment Security Score',
        before: '4/10',
        after: '9/10',
        improvement: '125% improvement',
        type: 'score',
        isPositive: true,
        icon: 'credit-card',
      },
      {
        id: 'customer-data-protection',
        label: 'Customer Data Protection',
        before: 'Basic',
        after: 'Advanced',
        improvement: 'Major improvement',
        type: 'score',
        isPositive: true,
        icon: 'user',
      },
      {
        id: 'pci-compliance',
        label: 'PCI DSS Compliance',
        before: 'Non-compliant',
        after: 'Compliant',
        improvement: 'Achieved compliance',
        type: 'percentage',
        isPositive: true,
        icon: 'check-circle',
      },
      {
        id: 'conversion-rate',
        label: 'Customer Conversion Rate',
        before: '2.1%',
        after: '2.8%',
        improvement: '33% increase',
        type: 'percentage',
        isPositive: true,
        icon: 'trending-up',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Complex e-commerce platform with multiple integrations',
      'Payment card data security requirements',
      'High volume of customer transactions',
      'Need to maintain customer trust and experience',
      'Legacy security controls',
    ],
    solutions: [
      'Implemented comprehensive payment security controls',
      'Enhanced customer data encryption and access controls',
      'Achieved PCI DSS compliance with proper documentation',
      'Improved security monitoring and alerting systems',
      'Conducted customer trust building initiatives',
    ],
    results: [
      {
        id: 'payment-security',
        title: 'Payment Security',
        description: 'Improved payment security score from 4/10 to 9/10',
        value: '125%',
        unit: 'improvement',
        impact: 'high',
        icon: 'credit-card',
      },
      {
        id: 'pci-compliance',
        title: 'PCI DSS Compliance',
        description: 'Achieved full PCI DSS compliance',
        value: '100%',
        unit: 'compliant',
        impact: 'high',
        icon: 'check-circle',
      },
      {
        id: 'customer-trust',
        title: 'Customer Trust',
        description: 'Increased customer conversion rate by 33%',
        value: '33%',
        unit: 'increase',
        impact: 'medium',
        icon: 'trending-up',
      },
      {
        id: 'data-protection',
        title: 'Data Protection',
        description:
          'Enhanced customer data protection with end-to-end encryption',
        value: 'Advanced',
        unit: 'protection level',
        impact: 'medium',
        icon: 'shield',
      },
    ] as CaseStudyResult[],
    testimonial: undefined,
    technologies: [
      'PCI DSS Framework',
      'Payment Security Tools',
      'Data Encryption',
      'Web Application Firewall',
      'Security Monitoring',
      'Customer Trust Analytics',
    ],
    caseStudyUrl: '/case-studies/ecommerce-security-audit',
    isFeatured: false,
    difficultyLevel: 'intermediate',
    compliance: ['PCI DSS', 'GDPR'],
    industry: 'Retail',
    projectSize: 'mid-market',
  },

  {
    id: 'government-cybersecurity-program',
    title: 'Government Cybersecurity Program',
    subtitle: 'National cybersecurity initiative for government agency',
    description:
      'Designed and implemented comprehensive cybersecurity program for government agency, including threat intelligence, incident response, and security awareness. The program significantly improved national security posture.',
    image: '/images/case-studies/government-cybersecurity-program.jpg',
    category: [
      'government',
      'incident-response',
      'network-security',
    ] as CaseStudyCategory[],
    client: clients[5],
    timeline: {
      startDate: '2023-06-01',
      endDate: '2024-06-01',
      duration: '1 year',
    },
    securityDomain: [
      'incident-response',
      'network-security',
      'compliance',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'threat-intelligence',
        label: 'Threat Intelligence Coverage',
        before: 'Basic',
        after: 'Advanced',
        improvement: 'Major improvement',
        type: 'score',
        isPositive: true,
        icon: 'target',
      },
      {
        id: 'incident-response',
        label: 'Incident Response Time',
        before: '4 hours',
        after: '30 minutes',
        improvement: '87% faster',
        type: 'time',
        isPositive: true,
        icon: 'alert-circle',
      },
      {
        id: 'security-awareness',
        label: 'Employee Security Awareness',
        before: '30%',
        after: '85%',
        improvement: '183% improvement',
        type: 'percentage',
        isPositive: true,
        icon: 'users',
      },
      {
        id: 'compliance-audit',
        label: 'Compliance Audit Score',
        before: '65%',
        after: '95%',
        improvement: '46% improvement',
        type: 'percentage',
        isPositive: true,
        icon: 'file-text',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Highly sensitive government data and systems',
      'Advanced persistent threats from nation-state actors',
      'Large distributed workforce',
      'Stringent compliance and audit requirements',
      'Need for zero security incidents',
    ],
    solutions: [
      'Implemented advanced threat intelligence platform',
      'Built 24/7 incident response center with automated workflows',
      'Conducted comprehensive security awareness program for 10,000+ employees',
      'Achieved 95% compliance audit score with proper documentation',
      'Established zero-trust architecture for all government systems',
    ],
    results: [
      {
        id: 'threat-intelligence',
        title: 'Threat Intelligence',
        description:
          'Implemented advanced threat intelligence with real-time monitoring',
        value: 'Advanced',
        unit: 'capability level',
        impact: 'high',
        icon: 'target',
      },
      {
        id: 'response-time',
        title: 'Response Time',
        description:
          'Reduced incident response time from 4 hours to 30 minutes',
        value: '87%',
        unit: 'faster',
        impact: 'high',
        icon: 'alert-circle',
      },
      {
        id: 'awareness-program',
        title: 'Security Awareness',
        description: 'Increased employee security awareness from 30% to 85%',
        value: '183%',
        unit: 'improvement',
        impact: 'medium',
        icon: 'users',
      },
      {
        id: 'compliance-achievement',
        title: 'Compliance Achievement',
        description: 'Achieved 95% compliance audit score',
        value: '95%',
        unit: 'score',
        impact: 'medium',
        icon: 'file-text',
      },
    ] as CaseStudyResult[],
    testimonial: undefined,
    technologies: [
      'Threat Intelligence Platforms',
      'SIEM Solutions',
      'Incident Response Automation',
      'Security Awareness Training',
      'Zero Trust Architecture',
      'Compliance Management',
    ],
    caseStudyUrl: '/case-studies/government-cybersecurity-program',
    isFeatured: false,
    difficultyLevel: 'expert',
    compliance: ['NIST', 'FISMA'],
    industry: 'Government',
    projectSize: 'enterprise',
  },

  {
    id: 'education-institution-security',
    title: 'Education Institution Security',
    subtitle: 'Cybersecurity program for university network',
    description:
      'Implemented comprehensive cybersecurity program for university, protecting student data and research while enabling academic innovation. The program balanced security with academic freedom requirements.',
    image: '/images/case-studies/education-security-program.jpg',
    category: [
      'education',
      'network-security',
      'compliance',
    ] as CaseStudyCategory[],
    client: clients[6],
    timeline: {
      startDate: '2023-09-01',
      endDate: '2024-03-31',
      duration: '7 months',
    },
    securityDomain: [
      'network-security',
      'compliance',
      'data-protection',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'student-data-protection',
        label: 'Student Data Protection',
        before: 'Basic',
        after: 'Advanced',
        improvement: 'Major improvement',
        type: 'score',
        isPositive: true,
        icon: 'graduation-cap',
      },
      {
        id: 'research-security',
        label: 'Research Data Security',
        before: 'Vulnerable',
        after: 'Protected',
        improvement: 'Complete protection',
        type: 'score',
        isPositive: true,
        icon: 'book',
      },
      {
        id: 'faculty-adoption',
        label: 'Faculty Security Adoption',
        before: '20%',
        after: '75%',
        improvement: '275% improvement',
        type: 'percentage',
        isPositive: true,
        icon: 'users',
      },
      {
        id: 'compliance-status',
        label: 'FERPA Compliance',
        before: 'At risk',
        after: 'Compliant',
        improvement: 'Achieved compliance',
        type: 'percentage',
        isPositive: true,
        icon: 'check-circle',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Large distributed network with 50,000+ users',
      'Need to balance security with academic freedom',
      'Protection of sensitive student and research data',
      'Limited IT security budget',
      'Diverse device ecosystem',
    ],
    solutions: [
      'Implemented network segmentation for different user groups',
      'Built comprehensive data protection for student and research data',
      'Conducted engaging security awareness for faculty and students',
      'Achieved FERPA compliance with proper data handling',
      'Implemented cost-effective security solutions',
    ],
    results: [
      {
        id: 'data-protection',
        title: 'Data Protection',
        description:
          'Enhanced student and research data protection to advanced level',
        value: 'Advanced',
        unit: 'protection level',
        impact: 'high',
        icon: 'shield',
      },
      {
        id: 'faculty-adoption',
        title: 'Faculty Adoption',
        description: 'Increased faculty security adoption from 20% to 75%',
        value: '275%',
        unit: 'improvement',
        impact: 'medium',
        icon: 'users',
      },
      {
        id: 'compliance-achievement',
        title: 'FERPA Compliance',
        description: 'Achieved full FERPA compliance',
        value: '100%',
        unit: 'compliant',
        impact: 'medium',
        icon: 'check-circle',
      },
      {
        id: 'research-protection',
        title: 'Research Protection',
        description:
          'Protected sensitive research data from unauthorized access',
        value: 'Complete',
        unit: 'protection',
        impact: 'medium',
        icon: 'book',
      },
    ] as CaseStudyResult[],
    testimonial: undefined,
    technologies: [
      'Network Segmentation',
      'Data Loss Prevention',
      'Security Awareness Platform',
      'FERPA Compliance Tools',
      'Endpoint Security',
      'Research Data Protection',
    ],
    caseStudyUrl: '/case-studies/education-security-program',
    isFeatured: false,
    difficultyLevel: 'intermediate',
    compliance: ['FERPA', 'COPPA'],
    industry: 'Education',
    projectSize: 'mid-market',
  },

  {
    id: 'iot-device-security-assessment',
    title: 'IoT Device Security Assessment',
    subtitle: 'Comprehensive security evaluation for IoT manufacturer',
    description:
      'Conducted security assessment for IoT device manufacturer, identifying vulnerabilities in device firmware and cloud infrastructure. Implemented security improvements to protect millions of connected devices.',
    image: '/images/case-studies/iot-device-security.jpg',
    category: [
      'technology',
      'iot-security',
      'secure-development',
    ] as CaseStudyCategory[],
    client: clients[7],
    timeline: {
      startDate: '2024-01-15',
      endDate: '2024-04-15',
      duration: '3 months',
    },
    securityDomain: [
      'iot-security',
      'secure-development',
      'network-security',
    ] as SecurityDomain[],
    metrics: [
      {
        id: 'device-vulnerabilities',
        label: 'Device Vulnerabilities',
        before: '12',
        after: '2',
        improvement: '83% reduction',
        type: 'count',
        isPositive: true,
        icon: 'cpu',
      },
      {
        id: 'firmware-security',
        label: 'Firmware Security Score',
        before: '3/10',
        after: '8/10',
        improvement: '167% improvement',
        type: 'score',
        isPositive: true,
        icon: 'code',
      },
      {
        id: 'cloud-security',
        label: 'Cloud Infrastructure Security',
        before: 'Basic',
        after: 'Advanced',
        improvement: 'Major improvement',
        type: 'score',
        isPositive: true,
        icon: 'cloud',
      },
      {
        id: 'customer-trust',
        label: 'Customer Trust Score',
        before: '6/10',
        after: '9/10',
        improvement: '50% improvement',
        type: 'score',
        isPositive: true,
        icon: 'users',
      },
    ] as CaseStudyMetric[],
    challenges: [
      'Complex IoT ecosystem with multiple device types',
      'Limited security expertise in IoT development',
      'Need to protect millions of deployed devices',
      'Rapid development cycles with security requirements',
      'Regulatory requirements for IoT devices',
    ],
    solutions: [
      'Conducted comprehensive firmware security analysis',
      'Implemented secure development lifecycle for IoT devices',
      'Enhanced cloud infrastructure security with zero-trust principles',
      'Built over-the-air security update capabilities',
      'Established IoT security compliance framework',
    ],
    results: [
      {
        id: 'vulnerability-reduction',
        title: 'Vulnerability Reduction',
        description: 'Reduced device vulnerabilities by 83%',
        value: '83%',
        unit: 'reduction',
        impact: 'high',
        beforeValue: '12',
        afterValue: '2',
        icon: 'trending-down',
      },
      {
        id: 'firmware-security',
        title: 'Firmware Security',
        description: 'Improved firmware security score from 3/10 to 8/10',
        value: '167%',
        unit: 'improvement',
        impact: 'high',
        icon: 'code',
      },
      {
        id: 'cloud-security',
        title: 'Cloud Security',
        description: 'Enhanced cloud infrastructure security to advanced level',
        value: 'Advanced',
        unit: 'security level',
        impact: 'medium',
        icon: 'cloud',
      },
      {
        id: 'customer-trust',
        title: 'Customer Trust',
        description: 'Increased customer trust score from 6/10 to 9/10',
        value: '50%',
        unit: 'improvement',
        impact: 'medium',
        icon: 'users',
      },
    ] as CaseStudyResult[],
    testimonial: undefined,
    technologies: [
      'IoT Security Frameworks',
      'Firmware Analysis Tools',
      'Secure OTA Updates',
      'Cloud Security',
      'Device Management',
      'Compliance Testing',
    ],
    caseStudyUrl: '/case-studies/iot-device-security',
    isFeatured: false,
    difficultyLevel: 'advanced',
    compliance: ['NIST IoT', 'GDPR'],
    industry: 'Technology',
    projectSize: 'smb',
  },
];

// Case studies configuration
export const CASE_STUDIES_CONFIG = {
  title: 'Case Studies & Security Projects',
  subtitle: 'Real-World Cybersecurity Success Stories',
  description:
    'Explore successful cybersecurity implementations that have protected organizations and prevented potential breaches. Each case study demonstrates measurable outcomes and proven security improvements.',
  showFilters: true,
  showSearch: true,
  showPagination: true,
  itemsPerPage: 6,
  animationSpeed: 0.6,
  enableLazyLoading: true,
  showClientLogos: true,
  showMetrics: true,
};

// Filter options for the case studies
export const CASE_STUDY_FILTERS = {
  categories: [
    { id: 'web-security', label: 'Web Security', count: 3, isActive: false },
    {
      id: 'network-security',
      label: 'Network Security',
      count: 3,
      isActive: false,
    },
    {
      id: 'cloud-security',
      label: 'Cloud Security',
      count: 2,
      isActive: false,
    },
    {
      id: 'incident-response',
      label: 'Incident Response',
      count: 2,
      isActive: false,
    },
    {
      id: 'secure-development',
      label: 'Secure Development',
      count: 2,
      isActive: false,
    },
    { id: 'compliance', label: 'Compliance', count: 4, isActive: false },
    { id: 'enterprise', label: 'Enterprise', count: 4, isActive: false },
    { id: 'healthcare', label: 'Healthcare', count: 1, isActive: false },
    { id: 'financial', label: 'Financial', count: 1, isActive: false },
    { id: 'technology', label: 'Technology', count: 2, isActive: false },
    { id: 'government', label: 'Government', count: 1, isActive: false },
    { id: 'education', label: 'Education', count: 1, isActive: false },
    { id: 'retail', label: 'Retail', count: 1, isActive: false },
    { id: 'startup', label: 'Startup', count: 1, isActive: false },
    { id: 'smb', label: 'Small Business', count: 1, isActive: false },
  ],
  securityDomains: [
    {
      id: 'web-application-security',
      label: 'Web Application Security',
      count: 3,
      isActive: false,
    },
    {
      id: 'network-security',
      label: 'Network Security',
      count: 3,
      isActive: false,
    },
    {
      id: 'cloud-security',
      label: 'Cloud Security',
      count: 2,
      isActive: false,
    },
    {
      id: 'incident-response',
      label: 'Incident Response',
      count: 2,
      isActive: false,
    },
    {
      id: 'secure-development',
      label: 'Secure Development',
      count: 2,
      isActive: false,
    },
    { id: 'compliance', label: 'Compliance', count: 4, isActive: false },
    { id: 'iot-security', label: 'IoT Security', count: 1, isActive: false },
    {
      id: 'mobile-security',
      label: 'Mobile Security',
      count: 0,
      isActive: false,
    },
    {
      id: 'data-protection',
      label: 'Data Protection',
      count: 4,
      isActive: false,
    },
    {
      id: 'identity-access-management',
      label: 'Identity & Access Management',
      count: 2,
      isActive: false,
    },
  ],
  industries: [
    { id: 'manufacturing', label: 'Manufacturing', count: 1, isActive: false },
    { id: 'healthcare', label: 'Healthcare', count: 1, isActive: false },
    {
      id: 'financial-services',
      label: 'Financial Services',
      count: 1,
      isActive: false,
    },
    { id: 'technology', label: 'Technology', count: 2, isActive: false },
    { id: 'retail', label: 'Retail', count: 1, isActive: false },
    { id: 'government', label: 'Government', count: 1, isActive: false },
    { id: 'education', label: 'Education', count: 1, isActive: false },
  ],
  projectSizes: [
    { id: 'startup', label: 'Startup', count: 1, isActive: false },
    { id: 'smb', label: 'Small Business', count: 1, isActive: false },
    { id: 'mid-market', label: 'Mid-Market', count: 2, isActive: false },
    { id: 'enterprise', label: 'Enterprise', count: 4, isActive: false },
  ],
  difficultyLevels: [
    { id: 'beginner', label: 'Beginner', count: 0, isActive: false },
    { id: 'intermediate', label: 'Intermediate', count: 3, isActive: false },
    { id: 'advanced', label: 'Advanced', count: 3, isActive: false },
    { id: 'expert', label: 'Expert', count: 2, isActive: false },
  ],
  compliance: [
    { id: 'soc-2', label: 'SOC 2', count: 2, isActive: false },
    { id: 'hipaa', label: 'HIPAA', count: 1, isActive: false },
    { id: 'pci-dss', label: 'PCI DSS', count: 1, isActive: false },
    { id: 'gdpr', label: 'GDPR', count: 2, isActive: false },
    { id: 'nist', label: 'NIST', count: 1, isActive: false },
    { id: 'fisma', label: 'FISMA', count: 1, isActive: false },
    { id: 'ferpa', label: 'FERPA', count: 1, isActive: false },
    { id: 'coppa', label: 'COPPA', count: 1, isActive: false },
    { id: 'iso-27001', label: 'ISO 27001', count: 1, isActive: false },
    { id: 'hitrust', label: 'HITRUST', count: 1, isActive: false },
  ],
};
